// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6BL2yoOAMrUAslusXWVigMjNYrj06adw',
    appId: '1:130193866403:web:45f50bd61cf8f642dfc916',
    messagingSenderId: '130193866403',
    projectId: 'handinhand-d6ded',
    authDomain: 'handinhand-d6ded.firebaseapp.com',
    storageBucket: 'handinhand-d6ded.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMswVw2SejvVw9VPDSDgzKH5TfedS9qc',
    appId: '1:130193866403:android:a92cc413b30dd50adfc916',
    messagingSenderId: '130193866403',
    projectId: 'handinhand-d6ded',
    storageBucket: 'handinhand-d6ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf08YnsSoArwZvosXETbfHt6QY8n6LHYg',
    appId: '1:130193866403:ios:af32e835237e09cbdfc916',
    messagingSenderId: '130193866403',
    projectId: 'handinhand-d6ded',
    storageBucket: 'handinhand-d6ded.appspot.com',
    iosBundleId: 'com.example.researchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf08YnsSoArwZvosXETbfHt6QY8n6LHYg',
    appId: '1:130193866403:ios:17795f39ab912023dfc916',
    messagingSenderId: '130193866403',
    projectId: 'handinhand-d6ded',
    storageBucket: 'handinhand-d6ded.appspot.com',
    iosBundleId: 'com.example.researchApp.RunnerTests',
  );
}
