// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY70p9yc_WT3SKf-GPZCOhP6EUBd5r6FU',
    appId: '1:644164481831:web:79aad2bb78974d0e8a6f02',
    messagingSenderId: '644164481831',
    projectId: 'educationalapp-77694',
    authDomain: 'educationalapp-77694.firebaseapp.com',
    storageBucket: 'educationalapp-77694.appspot.com',
    measurementId: 'G-LMDVP0HS7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_Cw4So5U4f1q-YXlEd4ltrIlB8aiMvk',
    appId: '1:644164481831:android:2b4e1408862842918a6f02',
    messagingSenderId: '644164481831',
    projectId: 'educationalapp-77694',
    storageBucket: 'educationalapp-77694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXU_FsyWH-HrQxPyS1hmTWfk7jLq-1Gd8',
    appId: '1:644164481831:ios:0fd292828e1d05a38a6f02',
    messagingSenderId: '644164481831',
    projectId: 'educationalapp-77694',
    storageBucket: 'educationalapp-77694.appspot.com',
    iosBundleId: 'com.example.researchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXU_FsyWH-HrQxPyS1hmTWfk7jLq-1Gd8',
    appId: '1:644164481831:ios:6ebe68435472590a8a6f02',
    messagingSenderId: '644164481831',
    projectId: 'educationalapp-77694',
    storageBucket: 'educationalapp-77694.appspot.com',
    iosBundleId: 'com.example.researchApp.RunnerTests',
  );
}
