// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD308l9WtsnRRFQR3RCDSw-bXGtdfnG6d8',
    appId: '1:434184537309:web:78a2f1d5d2f6c78830c734',
    messagingSenderId: '434184537309',
    projectId: 'handinhand-5cfb5',
    authDomain: 'handinhand-5cfb5.firebaseapp.com',
    storageBucket: 'handinhand-5cfb5.appspot.com',
    measurementId: 'G-147T1SFBYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zEEQ3dmRkbimbTxB8CFL7g8GVlURKyw',
    appId: '1:434184537309:android:355199817b61973730c734',
    messagingSenderId: '434184537309',
    projectId: 'handinhand-5cfb5',
    storageBucket: 'handinhand-5cfb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3a1FHyzg7aavNSQZw9DksPE_ebtY44Q',
    appId: '1:434184537309:ios:991de362e0db3a1b30c734',
    messagingSenderId: '434184537309',
    projectId: 'handinhand-5cfb5',
    storageBucket: 'handinhand-5cfb5.appspot.com',
    iosBundleId: 'com.example.researchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu3a1FHyzg7aavNSQZw9DksPE_ebtY44Q',
    appId: '1:434184537309:ios:fa041abecd0bf1d930c734',
    messagingSenderId: '434184537309',
    projectId: 'handinhand-5cfb5',
    storageBucket: 'handinhand-5cfb5.appspot.com',
    iosBundleId: 'com.example.researchApp.RunnerTests',
  );
}
